service: unident-app

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1

plugins:
  - serverless-s3-sync

custom:
  bucketName: unident-app
  s3Sync:
    - bucketName: unident-app
      localDir: dist/

resources:
  Resources:
    UnidentBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: unident-app
        # AccessControl: PublicRead
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
        OwnershipControls:
          Rules:
            - ObjectOwnership: ObjectWriter
        WebsiteConfiguration:
          IndexDocument: index.html
          ErrorDocument: index.html
    S3AccessPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: 
          Ref: UnidentBucket
        PolicyDocument:
          Statement:
            - Sid: PublicReadGetObject
              Effect: Allow
              Principal: '*'
              Action: 
                - s3:GetObject
                - s3:PutObject
              Resource: arn:aws:s3:::unident-app/*
    CloudFrontDistribution:
      Type: AWS::CloudFront::Distribution
      Properties:
        DistributionConfig:
          CNAMEs:
            - "clinicaunident.com.ar"
          Origins:
            - DomainName: unident-app.s3.amazonaws.com
              #OriginPath: "/index.html"
              Id:  unidentAPP
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
                OriginKeepaliveTimeout: 5
                OriginReadTimeout: 30
            - DomainName: unident-app.s3-website-us-east-1.amazonaws.com
              #OriginPath: "/index.html"
              Id:  unidentAPP-website
              CustomOriginConfig:
                HTTPPort: 80
                HTTPSPort: 443
                OriginProtocolPolicy: https-only
                OriginKeepaliveTimeout: 5
                OriginReadTimeout: 30
          Enabled: true
          Aliases:
            - "clinicaunident.com.ar"
          DefaultRootObject: index.html
          CustomErrorResponses:
            - ErrorCode: 404
              ResponseCode: 200
              ResponsePagePath: /index.html
          DefaultCacheBehavior:
            AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            TargetOriginId: unidentAPP
            ForwardedValues:
              QueryString: false
              Cookies:
                Forward: none
            ViewerProtocolPolicy: redirect-to-https
          ViewerCertificate:
            AcmCertificateArn: arn:aws:acm:us-east-1:339713137955:certificate/ebb98bf0-4096-45da-b43c-67bee4cef13f
            SslSupportMethod: sni-only
          HttpVersion: http2