name: deploy-to-aws
run-name: ${{ github.actor }} deploy a aws 
on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      CI: false
    steps:
      - name: 'Checkout to code folder'
        uses: actions/checkout@v3
      - name: Install AWS CLI
        run: |
          sudo apt-get update && \
          sudo apt-get install -y python3-pip && \
          pip3 install --upgrade --user awscli
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Install Serverless Framework and Packages
        run: |
          npm i -g serverless
          npm i
      - name: Install s3 plugin
        run: |
          sls plugin install -n serverless-s3-sync
      - name: Build React App
        run: |
          npm run build
      - name: Deploys serverless Framework
        run: |
          sls deploy --param="stage=prod" --verbose
